abstract: Kwiki LivedoorAuth integration
author: Kazuhiro Osawa <ko@yappo.ne.jp>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: unknown
name: Kwiki-LivedoorAuth
no_index: 
  directory: 
    - inc
    - t
requires: 
  URI::Escape: 0
  WebService::Livedoor::Auth: 0
version: 0.01
